//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Employee
{
    public int ID { get; set; }
    public string FullName { get; set; }
    public Nullable<System.DateTime> DateOfBirth { get; set; }
    public string Gender { get; set; }
    public string National { get; set; }
    public string Phone { get; set; }
    public string Address { get; set; }
    public string Qualification { get; set; }
    public Nullable<decimal> Salary { get; set; }
}
